name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.3
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build shared package
        run: pnpm run build:shared
      - name: Type check
        run: pnpm tsc --noEmit
      - name: Build shared package
        run: pnpm run build:shared

  lint:
    runs-on: ubuntu-latest
    needs: type-check
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.3
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm eslint . --ext .ts,.tsx

  test:
    runs-on: ubuntu-latest
    needs: type-check
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.3
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Setup test env
        run: |
          echo "DATABASE_URL=postgres://user:pass@localhost:5432/db" >> .env
          echo "JWT_SECRET=testsecret" >> .env
          echo "API_BASE_URL=http://localhost:3000" >> .env
          echo "FRONTEND_BASE_URL=http://localhost:5173" >> .env
      - name: Build shared package
        run: pnpm run build:shared
      - name: Unit & Integration tests
        run: pnpm test
      - name: Build project
        run: pnpm run build

  security:
    runs-on: ubuntu-latest
    needs: type-check
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.3
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Security audit
        run: pnpm audit --audit-level=high

  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.3
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check code style
        run: npx prettier --check . || true
      - name: Lint check
        run: npx eslint . --ext .ts,.tsx || true